### ISSUE TITLE
Multiple popups making Sublime Text unresponsive/unusable 

### ISSUE THREAD

**Issue by alextegelid** [dvcrn/sublimious#10] opened 2015-09-21 08:55 UTC
I noticed this shortly after installing sublimious. The amount of popups in the screenshot is nothing compared to the amount that would appear from time to time. It could possibly relate to the `Packages/User` folder being symlinked to Dropbox.

Unfortunately I had to remove sublimious to get Sublime Text running again. I use it most of my workdays, so I need it up'n'running.

![skarmavbild 2015-09-18 kl 14 54 13](https://cloud.githubusercontent.com/assets/7058721/9988022/5cac5fda-604d-11e5-9a18-9d244dd6a8ce.png)

**Comment by dvcrn** [comment] 2015-09-21 14:54
Sadly this is known during initial installation and not related to Dropbox. The problem is that sublimious is taking control over package control and excludes a bunch of stuff or sets settings for packages that are not there yet. Package control tries to resolve everything but until that is done you'll get a bunch of these (sometimes). 

For this you'll have to close the popups and restart sublime text. Working on a solution but not quite sure how to efficiently get rid of this while at the same time get the behavior we want.

**Comment by dvcrn** [comment] 2015-09-21 14:56
(Also currently inside the todos here - https://github.com/dvcrn/sublimious/blob/master/README.md)

**Comment by alextegelid** [comment] 2015-09-21 16:35
Alright! I didn't connect my errors to the ones you mention in the todos. It felt they appeared after having run sublimous for at least a couple of minutes.

I close this issue since it's already known. Also I'll keep track of this project and jump in for a test run now and then 😉

**Comment by dvcrn** [comment] 2015-09-22 01:22
I'll re-open this until we have a solution (for reference). 

@alextegelid did you by chance check the console to see which packages exactly are causing this error?

**Comment by dvcrn** [comment] 2015-09-30 01:59
@alextegelid I published version 0.4.1 to package control. This changes the way packages are resolved and should hopefully get rid of the popups. 
If you have some free time, do you mind giving it another shot to see if you still run into this problems? In my tests the `ignored_packages` errors are gone

**Comment by alextegelid** [comment] 2015-09-30 06:55
That sounds great! Unfortunately I can't try it right now due to a massive backlog at work ;) When I get the time I'll set up a new user on my laptop to separate the two Sublime Text setups; one for work and one for testing sublimious

**Comment by dvcrn** [comment] 2015-10-01 04:25
Restored my old pre-sublimious config and installed sublimious through package control on top. The result: Not a single popup, not even a missing color scheme warning (there were quite a few before!). Seems like the latests changes worked gold. I'm closing this issue. 

If you have more issues, please let me know :)

**Closed as completed by dvcrn** 2015-10-01 04:25 UTC
Labels: bug
